name: F1 Weekend Live Update
on:
  schedule:
    - cron: '*/5 * * * 5,6,0' # 금, 토, 일 5분마다 실행
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run Script
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python f1_live.py
